name: file_sharing
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.2.3
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  url_strategy: ^0.3.0
  hive_flutter: ^1.1.0
  firebase_core: ^3.3.0
  flutter_smart_dialog: ^4.9.8
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  firebase_auth: ^5.1.4
  data_table_2: ^2.5.15
  file_picker: ^8.0.7
  syncfusion_flutter_pdfviewer: ^26.2.9
  file_saver: ^0.2.13
  url_launcher: ^6.3.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true



  assets:
    - assets/images/

  fonts:
      - family: OpenSans
        fonts:
          - asset: assets/fonts/OpenSans-Regular.ttf
          - asset: assets/fonts/OpenSans-Bold.ttf
          - asset: assets/fonts/OpenSans-Light.ttf
      - family: Raleway
        fonts:
          - asset: assets/fonts/Raleway-Bold.ttf
          - asset: assets/fonts/Raleway-Regular.ttf
          - asset: assets/fonts/Raleway-Light.ttf



flutter_native_splash:
    color: "#ffffff"
    image: assets/images/icon.png
    image_web: assets/images/hostel_logo_white_t.png
    android: true
    ios: true
    web: true
    android_12:
  #dart run flutter_native_splash:create

flutter_launcher_icons:
    android: "launcher_icon"
    ios: false
    image_path: "assets/images/icon_t.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
    web:
      generate: true
      image_path: "assets/images/icon_t.png"
      background_color: "#hexcode"
      theme_color: "#hexcode"
  #    flutter pub run flutter_launcher_icons
flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: assets.dart
  field_prefix: