// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEAiHr4lDbi4RNzDTh5eWWCMZtxHDZteA',
    appId: '1:86721664528:web:192560e7fc8802f5a89c95',
    messagingSenderId: '86721664528',
    projectId: 'file-net-97e98',
    authDomain: 'file-net-97e98.firebaseapp.com',
    storageBucket: 'file-net-97e98.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPlxHGGYpv0LTHeoPwDm8dPAuPSOUbYWo',
    appId: '1:86721664528:android:2092ea42266a1ed2a89c95',
    messagingSenderId: '86721664528',
    projectId: 'file-net-97e98',
    storageBucket: 'file-net-97e98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRjq0nuYRS23ySLDQ4VfmtIYOZocnFTk8',
    appId: '1:86721664528:ios:e9eb93c5a75d4a32a89c95',
    messagingSenderId: '86721664528',
    projectId: 'file-net-97e98',
    storageBucket: 'file-net-97e98.firebasestorage.app',
    iosBundleId: 'com.example.fileSharing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRjq0nuYRS23ySLDQ4VfmtIYOZocnFTk8',
    appId: '1:86721664528:ios:e9eb93c5a75d4a32a89c95',
    messagingSenderId: '86721664528',
    projectId: 'file-net-97e98',
    storageBucket: 'file-net-97e98.firebasestorage.app',
    iosBundleId: 'com.example.fileSharing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEAiHr4lDbi4RNzDTh5eWWCMZtxHDZteA',
    appId: '1:86721664528:web:99bf3b10b5911d26a89c95',
    messagingSenderId: '86721664528',
    projectId: 'file-net-97e98',
    authDomain: 'file-net-97e98.firebaseapp.com',
    storageBucket: 'file-net-97e98.firebasestorage.app',
  );
}
